name: 游 Despliegue Autom치tico (FTP)

on:
  push:
    branches:
      - main  # Se ejecuta cuando haces push a la rama 'main'

jobs:
  web-deploy:
    name: 游꿀 Desplegar a Hosting
    runs-on: ubuntu-latest
    steps:
    - name: 游뚴 Obtener el c칩digo m치s reciente
      uses: actions/checkout@v4

    - name: 游늭 Sincronizar archivos v칤a FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # server-dir: /public_html/  # Descomenta y ajusta si tu web est치 en una subcarpeta
        exclude: |
          **/.git*
          **/.git*/**
          **/.github/**
          **/node_modules/**
          **/tests/**
          README.md
          *.md
          *.sql
          # Excluimos la configuraci칩n local para no romper la de producci칩n
          # config_mysql.php 
